spring:
  jpa:
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  main:
    allow-circular-references: true

server:
  servlet:
    encoding:
      charset: UTF-8
      force-response: true
  port: 8081
